# Generated by Django 3.1.7 on 2021-02-19 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Item', max_length=100, null=True)),
                ('description', models.CharField(help_text='Description of the Item', max_length=1000, null=True)),
                ('total', models.IntegerField(help_text='Total amount of the item available', null=True)),
                ('deficit', models.IntegerField(help_text='Total amount of the item credited', null=True)),
                ('price', models.IntegerField(help_text='Price of the Item', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Please input only numbers character type.', null=True)),
                ('amount', models.IntegerField(help_text='Please input only numbers character type.', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.item')),
            ],
        ),
    ]
